### ISSUE TITLE
wordsToNumbers('xxxxxxx one hundred') = null

### ISSUE THREAD

**Issue by bhoomika911** [finnfiddle/words-to-numbers#10]
Hi...

This is great package for word to number conversion.But is there possible that if there is word like xxxxx which is not related to any number is return same as it passed like....

**Expected** 
wordsToNumbers('xxxxxxx one hundred') = xxxxxxx 100

**Current output**
wordsToNumbers('xxxxxxx one hundred') = null

Can any one help?

**Comment by finnfiddle** [comment]
sorry for the delay, I will be pushing a fix tomorrow. Completely refactored the whole library using ohm.js so now things will work much better

**Comment by finnfiddle** [comment]
fixed in fc621fed10c9aa2047059da35472de59f48351ee - closing. thanks for the feedback
