### ISSUE TITLE
Need to add a space at the end to make it work

### ISSUE THREAD

**Issue by ibmua** [finnfiddle/words-to-numbers#11]
'digit one' will not work, but 'digit one ' will. Bug.

**Comment by ibmua** [comment]
I would also highly advice making turning 'a' into 1s optional.

**Comment by ibmua** [comment]
Also, stuff like one-thirty doesn't work. Should be 1 30, got 31.

**Comment by ibmua** [comment]
'thousand' / 'million' / 'billion' => 0

Incredible!

**Comment by finnfiddle** [comment]
sorry for the delay, I will be pushing a fix tomorrow. Completely refactored the whole library using ohm.js so now things will work much better

**Comment by finnfiddle** [comment]
fixed in fc621fed10c9aa2047059da35472de59f48351ee (v1.2.2 on npm) everything except for "one thirtieth". Im treating fractions as a feature and will get to them sometime in the near future. closing this issue because the bugs you found are now fixed. thanks for the feedback
