### ISSUE TITLE
Implied hundreds, better support for hundred-thousands

### ISSUE THREAD

**Issue by exogen** [finnfiddle/words-to-numbers#18]
Hi @finnfiddle! I'm considering using `words-to-numbers` instead of porting some code of mine from another language to JS. I thought you might be interested in these additional test cases I supported in my old code that maybe `words-to-numbers` could support as well.

One feature is "implied hundreds," because it's very common to omit the explicit "hundred" when speaking naturally in English. For example, in "nineteen eighty four", it's implied that the number is actually "nineteen **hundred** eighty four". Or when counting high numbers, it's often skipped for brevity: "one thirty one, one thirty two, one thirty three". More examples, with current behavior shown:

```js
> wordsToNumbers('nineteen eighty four')
'19 84' // Expected: 1984 (number), instead got string with two numbers.

> wordsToNumbers('one thirty')
'1 30' // Expected: 130 (number), instead got string with two numbers.

> wordsToNumbers('six sixty two')
'6 62' // Expected: 662 (number), instead got string with two numbers.

> wordsToNumbers('ten twelve')
'10 12' // Expected: 1012 (number), instead got string with two numbers.

> wordsToNumbers('nineteen ten')
'19 10' // Expected: 1910 (number), instead got string with two numbers.

> wordsToNumbers('twenty ten')
30 // Expected: 2010 (number), instead got 20 + 10.

> wordsToNumbers('twenty seventeen')
37 // Expected: 2017 (number), instead got 20 + 17.

> wordsToNumbers('twenty twenty')
'20 20' // Expected: 2020 (number), instead got string with two numbers.

> wordsToNumbers('twenty twenty one')
'20 21' // Expected: 2021 (number), instead got string with two numbers.

> wordsToNumbers('fifty sixty three')
'50 63' // Expected: 5063 (number), instead got string with two numbers.

> wordsToNumbers('one thirty thousand')
'1 30000' // OK. Other magnitudes may not follow implied hundreds. Nobody talks this way.

> wordsToNumbers('nineteen eighty thousand')
'19 80000' // OK. Other magnitudes may not follow implied hundreds. Nobody talks this way.
```

The other feature is better support for hundred-thousands. Current behavior:

```js
> wordsToNumbers('one hundred thousand')
'100 1000' // Expected: 100000 (number), instead got string with two numbers.

> wordsToNumbers('one hundred two thousand')
2100 // Expected: 102000 (number), instead got 100 + 2000.

> wordsToNumbers('one hundred and two thousand')
2100 // Same result with "and".
```

Happy to work on this in a PR if you're interested.

**Comment by finnfiddle** [comment]
@exogen sorry for the delay on this one - I just missed it somehow. I am happy to add more functionality and would welcome any PRs. However, I foresee a problem with these added features. Currently, when you run `wordsToNumbers("some string")` if the whole string is composed of a contiguous list of words that can be evaluated as one number then it will return the converted number as a Number type (eg 100000). However, if the list of words is not a contiguous list of words from the same number (eg `"one hundred and two thousand"`) then it will replace each individual number word range and return a string (eg `"100 and 2000"`).
Which brings me to the problem: there are 2 ways to interpret `'twenty seventeen'`. Either as `2017` or as `"20 17"`.
I suggest having an added option to enable/disable implied hundreds/thousands/(what to call them?). Do you have other ideas?

**Comment by exogen** [comment]
@finnfiddle Nope, I was anticipating an option as well, for this reason!

**Comment by exogen** [comment]
@finnfiddle Sure thing, I'll see what I can do this week

**Comment by finnfiddle** [comment]
just to let you know Im working on this and it's taking some time because it's quite a tricky nut to crack!

**Comment by rajeeb-ta** [comment]
is there any possibility to add "nineteen hundred" coveted to 1900.
I hope some people use this way rather than saying 'thousand nine hundred'

**Comment by finnfiddle** [comment]
Ive been working on it - just had a lot of other work recently. Will
definitely ship the full inplied hundreds functionality in the near future

**Comment by finnfiddle** [comment]
Partially supported now in v1.5.0. These cases will work:
```
nineteen eighty four
one thirty
six sixty two
ten twelve
nineteen ten
twenty ten
twenty seventeen
twenty twenty
twenty twenty one
fifty sixty three
fifty sixty
three thousand
fifty sixty three thousand
one hundred thousand```

these dont yet:
```
one thirty thousand
nineteen eighty thousand
one hundred two thousand
one hundred and two thousand```

Please open another ticket if you want better support

**Comment by karmadice** [comment]
I am using v 1.5.1 and its still not working for me

**Comment by finnfiddle** [comment]
@karmadice can you be more specific? Which numbers exactly are not working? Here you can see all tests that are passing https://github.com/finnfiddle/words-to-numbers/blob/master/src/__tests__/index.js
