### ISSUE TITLE
Replacement in strings is inconsistent and/or throws error

### ISSUE THREAD

**Issue by guomo** [finnfiddle/words-to-numbers#20]
Looks like the replacement of numbers in an arbitrary string isn't working properly:

```
> wordsToNumbers('Fifty People, One Question: Brooklyn')
Line 1, col 1:
> 1 | Fifty
      ^
Expected end of input
Line 1, col 1:
> 1 | One
      ^
Expected end of input
'Fifty People, One Question: Brooklyn'
```

I would like to use this library to replace number-ish words to numerals in movie titles. These titles fail as well:

- Model Fifty-One Fifty-Six
- Fifty Million Frenchmen
- A Thousand and One Wives
- Ten Thousand Pictures of You

Seems to be an issue with case as well. e.g. the line below doesn't produce an error, but it doesn't replace the number as promised in the docs.

```
wordsToNumbers('Ten Thousand Pictures of You'.toLowerCase())
10000
```

**Comment by finnfiddle** [comment]
@guomo this should be fixed now with v1.4.1
