### ISSUE TITLE
Any junk value is defaulted to one. can it return null or undefined?

### ISSUE THREAD

**Issue by ubreddy** [finnfiddle/words-to-numbers#5]

**Comment by finnfiddle** [comment]
sorry for the delay, I will be pushing a fix tomorrow. Completely refactored the whole library using ohm.js so now things will work much better

**Comment by finnfiddle** [comment]
fixed in fc621fed10c9aa2047059da35472de59f48351ee (v1.2.2 on npm) - I made it return the original junk value - I think that is the most logical. You can always check it against the original input to see if anything was converted. thanks for the feedback
