### ISSUE TITLE
magnitude words return 0

### ISSUE THREAD

**Issue by ubreddy** [finnfiddle/words-to-numbers#6]
thousand
million
billion 

if input as single words return zero.

**Comment by finnfiddle** [comment]
sorry for the delay - I missed this somehow. will look into it

**Comment by finnfiddle** [comment]
again sorry for the delay, I will be pushing a fix tomorrow. Completely refactored the whole library using ohm.js so now things will work much better

**Comment by finnfiddle** [comment]
fixed in fc621fed10c9aa2047059da35472de59f48351ee (v1.2.2 on npm) - closing. thanks for the feedback
